Repository cloudfoundry/docs-cf-admin, pull requests merged in 2020-10, with the labels that each got.

#183 WebSockets are not supported with route services
  supporting-websockets.html.md.erb
Labels: in progress

#194 Remove "Skip SSL Certificate Verification"
  troubleshooting-router-error-responses.html.md.erb
Labels: scheduled

#193 Remove redundant gorouter arch doc
  docker.html.md.erb
  troubleshooting-router-error-responses.html.md.erb
Labels: in progress

#195 Update TCP routing docs for reservable ports
  enabling-tcp-routing.html.md.erb
Labels: unscheduled
